### ISSUE TITLE
[BUG] - Microsoft Todo CTD on moving tasks

### ISSUE THREAD

**Issue by rsoyxihnark** [Atlas-OS/Atlas#1284]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Microsoft Todo crashes on moving tasks position around the list.

### Steps to reproduce

![Animation](https://github.com/user-attachments/assets/44e43f7c-14f4-4932-b4fa-4f3f9b5279d4)

### Expected behavior

Task being moved with moved is moved

### Actual behavior

Crashes to desktop

### Atlas Version

Atlas v0.4.1 for Windows 10 22H2

### Desktop information

i711800H 64 GB RAM 2 TB storage RTX3070

**Comment by TheyCreeper** [comment]
Did the issue ever go away (for example with an update)? I do not get this issue on my end
