### ISSUE TITLE
Main TODO

### ISSUE THREAD

**Issue by Zusier** [Atlas-OS/Atlas#64]
Just a TODO Tracker, ignore.

- [x] Prompt instead of automatically disabling Wi-Fi
- [x] Migrate all invalid input checks to :invalidInput
- [x] Rid of aria2 dependency
- [ ] Open shell skin
